### ISSUE TITLE
`servers` check times out on large clouds

### ISSUE THREAD

**Issue by przemeklal** [canonical/charm-openstack-service-checks#160]
On large clouds check_servers can time out (the default is 10s which is often not enough to query all servers and check their status), it would be better if the charm could run the checks in a cronjob and read the results from a cache file (similarly to Octavia checks).

**Comment by zxhdaze** [comment]
Close this issue because openstack-service-check is no longer actively developed. We are moving checks to openstack-exporter. You can file a new feature request in the new [charm](https://github.com/canonical/openstack-exporter-operator), in the way that the new charm can provide the functionality you need.
You can also create alerts on [cos-configuration-k8s-operator](https://github.com/canonical/cos-configuration-k8s-operator)to monitor single servers if you install openstack-exporter-operator.
